"""
title: OpenAI Sora 2 Manifold
description: Pipe Function to enable video generation with state persistence via Companion Filter.
author: Dolfies
version: 0.1.0
license: MIT
requirements: typing, pydantic, openai, Pillow, opencv-python, loguru
"""
# Based on https://github.com/masaoki/sora2-openwebui, MIT

from __future__ import annotations

import base64
import asyncio
import io
import re
import uuid
from typing import Literal
from pydantic import BaseModel, Field
from openai import AsyncOpenAI
from PIL import Image, UnidentifiedImageError
from loguru import logger
from fastapi import Request
from open_webui.storage.provider import Storage
from open_webui.models.files import Files, FileForm
from open_webui.models.users import Users
from open_webui.models.chats import Chats


class Pipe:
    class Valves(BaseModel):
        OPENAI_API_KEY: str = Field(default="", description="OpenAI API Key")
        DURATION: str = Field(
            default="12", description="Video duration in seconds. 4, 8, or 12."
        )
        BASE_URL: str = Field(default="https://api.openai.com/v1")

    class UserValves(BaseModel):
        ORIENTATION: Literal["landscape", "portrait"] = Field(
            default="landscape", description="Video orientation: landscape or portrait"
        )

    def __init__(self):
        self.type = "manifold"
        self.valves = self.Valves()
        self.emitter = None
        self.remix = False
        self.vid = ""

    async def emit_status(self, message="", done=False):
        if self.emitter:
            await self.emitter(
                {
                    "type": "status",
                    "data": {
                        "description": message,
                        "hidden": False,
                        "status": "completion" if done else "in_progress",
                        "done": done,
                    },
                }
            )

    async def pipes(self):
        return [
            {"id": "sora-2", "name": "Sora 2"},
            {"id": "sora-2-pro", "name": "Sora 2 Pro"},
        ]

    def _orientation_size(self, model: str, orientation: str) -> tuple[int, int]:
        o = orientation.lower()
        if model == "sora-2":
            return (1280, 720) if o == "landscape" else (720, 1280)
        return (1792, 1024) if o == "landscape" else (1024, 1792)

    def _adjust_size(self, input: bytes, target_size: tuple[int, int]) -> bytes | None:
        try:
            img = Image.open(io.BytesIO(input))
        except (UnidentifiedImageError, ValueError):
            logger.error("Error: Invalid image data.")
            return None
        if img.mode == "RGBA":
            background = Image.new("RGB", img.size, (255, 255, 255))
            background.paste(img, mask=img.split()[3])
            img = background
        original_width, original_height = img.size
        original_aspect = original_width / original_height
        target_width, target_height = target_size
        target_aspect = target_width / target_height
        if original_aspect > target_aspect:
            new_width = int(target_aspect * original_height)
            offset = (original_width - new_width) / 2
            crop_box = (offset, 0, original_width - offset, original_height)
        else:
            new_height = int(original_width / target_aspect)
            offset = (original_height - new_height) / 2
            crop_box = (0, offset, original_width, original_height - offset)
        cropped_img = img.crop(crop_box)
        resized_img = cropped_img.resize(target_size, Image.Resampling.LANCZOS)
        output_buffer = io.BytesIO()
        resized_img.save(output_buffer, format="PNG")
        return output_buffer.getvalue()

    def _find_last_video_id(self, chat_id: str, user_id: str) -> str:
        """
        Scans the chat history via DB to find the last video generated by this pipe.
        It checks the 'info' field of ASSISTANT messages.
        """
        if not chat_id or not user_id:
            return ""

        chat = Chats.get_chat_by_id_and_user_id(id=chat_id, user_id=user_id)
        if not chat:
            return ""

        chat_data = chat.chat
        messages = chat_data.get("messages", [])

        for msg in reversed(messages):
            # We look for ASSISTANT messages
            if msg.get("role") == "user":
                continue

            info = msg.get("info")
            if info and isinstance(info, dict) and "sora_video_id" in info:
                vid = info["sora_video_id"]
                logger.info(f"Found Sora Remix candidate: {vid}")
                return vid

        return ""

    def _extract_prompt(self, messages: list[dict[str, str]]) -> tuple[str, str]:
        text: str = ""
        image: bytes | None = None
        for msg in messages:
            content = msg.get("content")
            is_list = isinstance(content, list)
            if is_list:
                text_item = "\n".join(
                    p.get("text") for p in content if p["type"] == "text"
                )
            else:
                text_item = content

            if msg.get("role") != "user":
                continue

            text = text_item
            if is_list:
                image_here = next(
                    (
                        p.get("image_url").get("url", "")
                        for p in content
                        if p["type"] == "image_url"
                    ),
                    None,
                )
                if image_here:
                    image = image_here
            else:
                match = re.search(
                    r"!\[[^\]]*\]\((data:([^;]+);base64,([^)]+))\)", str(content)
                )
                if match:
                    image = match[1]
                    sp = match.span(1)
                    text = content[: sp[0]] + content[sp[1] :]
        return text, image

    async def _poll_video(self, openai, video_id):
        last_progress = -1
        while True:
            await asyncio.sleep(3)
            v = await openai.videos.retrieve(video_id)
            if v.status not in ("in_progress", "queued"):
                return v
            current_progress = getattr(v, "progress", 0)
            try:
                current_progress = int(current_progress)
            except:
                current_progress = 0
            if current_progress > last_progress:
                last_progress = current_progress
                await self.emit_status(f"⏳ Progress {current_progress} %")

    async def generate_video(self, prompt, model, size, input_ref):
        if self.remix:
            await self.emit_status("🖼️ Remixing video...")
        else:
            await self.emit_status("🖼️ Generating video...")
        if not self.valves.OPENAI_API_KEY:
            return "Error: Missing OPENAI_API_KEY", None
        openai = AsyncOpenAI(
            api_key=self.valves.OPENAI_API_KEY, base_url=self.valves.BASE_URL
        )
        try:
            if self.remix and self.vid:
                video = await openai.videos.remix(video_id=self.vid, prompt=prompt)
            else:
                params = {
                    "model": model,
                    "prompt": prompt,
                    "seconds": str(self.valves.DURATION),
                    "size": f"{size[0]}x{size[1]}",
                }
                if input_ref:
                    params["input_reference"] = ("input.png", input_ref, "image/png")
                video = await openai.videos.create(**params)
            video = await self._poll_video(openai, video.id)
            if video.status == "failed":
                await self.emit_status("❌ Video generation failed", done=True)
                logger.error(f"{model} failed. {video}")
                try:
                    err = video.error.message
                except Exception as e:
                    err = str(e)
                return err, None
            body = await openai.videos.download_content(video.id, variant="video")
            data = await body.aread()
            return data, video.id
        except Exception as e:
            await self.emit_status("❌ Video generation failed", done=True)
            return str(e), None

    async def pipe(
        self,
        body: dict,
        __user__: dict,
        __request__: Request,
        __event_emitter__=None,
        __metadata__: dict = None,
    ):
        self.emitter = __event_emitter__
        user = Users.get_user_by_id(__user__["id"])
        chat_id = __metadata__.get("chat_id")

        user_valves = __user__["valves"]
        model_id = body.get("model", "sora-2")
        model = "sora-2-pro" if model_id == "sora-2-pro" else "sora-2"
        size = self._orientation_size(model, user_valves.ORIENTATION)

        self.remix = False
        self.vid = ""
        last_vid = self._find_last_video_id(chat_id, user.id)
        if last_vid:
            self.vid = last_vid
            self.remix = True

        prompt, img = self._extract_prompt(body.get("messages", []))

        if img:
            self.remix = False
            self.vid = ""

        img_bin = None
        if img:
            m = re.search(";base64,(.*)$", img)
            if m:
                img_bin = self._adjust_size(base64.b64decode(m.group(1)), size)

        out, vid = await self.generate_video(prompt, model, size, img_bin)

        if isinstance(out, str):
            return out

        file_id = str(uuid.uuid4())
        filename = f"{file_id}.mp4"
        md = {
            "OpenWebUI-User-Email": user.email,
            "OpenWebUI-User-Id": user.id,
            "OpenWebUI-User-Name": user.name,
            "OpenWebUI-File-Id": file_id,
            "OpenWebUI-Video-Id": vid,
        }
        _, path = Storage.upload_file(io.BytesIO(out), filename, md)
        Files.insert_new_file(
            user.id,
            FileForm(
                id=file_id,
                filename=filename,
                path=path,
                data={},
                meta={
                    "name": filename,
                    "content_type": "video/mp4",
                    "size": len(out),
                    "data": md,
                },
            ),
        )

        # Store ID in app.state for the Companion Filter
        if __metadata__ and "message_id" in __metadata__:
            msg_id = __metadata__["message_id"]
            key = f"sora_video_id_{chat_id}_{msg_id}"
            logger.info(f"Storing video ID {vid} in state key: {key}")
            setattr(__request__.app.state, key, vid)

        if __event_emitter__:
            await self.emit_status("Video generated", done=True)

        return f"""
        <video>
            /api/v1/files/{file_id}/content
        </video>
        """
